name: Run Tests on Pull Request on main

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:   
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Checkout repository 
        uses: actions/checkout@v4
      
      - name: Install python
        run: uv python install

      - name: Set up project structure
        run: uv sync

      - name: Run tests
        run: uv run pytest tests/
